[build-system]
requires = ["setuptools>=70", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jasna"
version = "0.4.0-rc3"
description = "Jasna"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "torch==2.9.1",
  "tensorrt==10.13.3.9.post1",
  "torch-tensorrt==2.9.0",
  "av>=16.1.0",
  "numpy",
  "transformers>=5",
  "mmengine==0.10.7",
  "opencv-python",
  "tqdm"
]

[project.scripts]
jasna = "jasna.main:main"

[project.optional-dependencies]
dev = [
  "pyinstaller>=6.0",
  "pytest",
  "pytest-cov",
]

[tool.setuptools]
packages = ["jasna", "jasna.mosaic", "jasna.restorer", "jasna.trt"]

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
  "ignore:'maxsplit' is passed as positional argument:DeprecationWarning:mmengine\\.utils\\.misc",
]

