[build-system]
requires = ["setuptools>=70", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jasna"
version = "0.1.1"
description = "Jasna"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "torch",
  "tqdm"
]

[project.scripts]
jasna = "jasna.main:main"

[project.optional-dependencies]
dev = [
  "pyinstaller>=6.0",
]

[tool.setuptools]
packages = ["jasna", "jasna.mosaic", "jasna.restorer", "jasna.trt"]

